FROM python:3.11.3-slim-bullseye

ARG POOL_NAME
ARG PREFECT_API_KEY
ARG ACCOUNT_ID
ARG WORKSPACE_ID
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100

ENV POOL_NAME=${PREFECT_POOL_NAME} \
    PREFECT_API_KEY=${PREFECT_API_KEY} \
    ACCOUNT_ID=${ACCOUNT_ID} \
    WORKSPACE_ID=${WORKSPACE_ID} \
    PREFECT_API_URL="https://api.prefect.cloud/api/accounts/${ACCOUNT_ID}/workspaces/${WORKSPACE_ID}"

ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
    AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
    AWS_DEFAULT_REGION="us-east-1"

COPY requirements.txt .
RUN pip install -r requirements.txt

CMD prefect agent start --pool ${POOL_NAME}
